name: 'DojoCardIndex-Terraform Deployment'

on:
  workflow_dispatch:

jobs:
  init-validate-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_admin_password: ${{ secrets.DB_ROOT_PASS }}
          TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          TF_VAR_tenant_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          TF_VAR_cloudinary_cloud_name: ${{ secrets.TF_VAR_CLOUDINARY_CLOUD_NAME }}
          TF_VAR_cloudinary_api_key: ${{ secrets.TF_VAR_CLOUDINARY_API_KEY }}
          TF_VAR_cloudinary_api_secret: ${{ secrets.TF_VAR_CLOUDINARY_API_SECRET }}

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: deployment/tfplan

  apply:
    runs-on: ubuntu-latest
    needs: init-validate-plan
    defaults:
      run:
        working-directory: ./deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: deployment

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_admin_password: ${{ secrets.DB_ROOT_PASS }}
          TF_VAR_subscription_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          TF_VAR_tenant_id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          TF_VAR_cloudinary_cloud_name: ${{ secrets.TF_VAR_CLOUDINARY_CLOUD_NAME }}
          TF_VAR_cloudinary_api_key: ${{ secrets.TF_VAR_CLOUDINARY_API_KEY }}
          TF_VAR_cloudinary_api_secret: ${{ secrets.TF_VAR_CLOUDINARY_API_SECRET }}
